services:
  - type: web
    name: telegram-bot-iss2
    env: python
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: MY_BOT_TOKEN
        sync: false
