services:
  - type: web
    name: telegram-bot-iss2
    env: python
    region: frankfurt
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: MY_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
